"""Embed stimulus sets in experimental time (contracts §4.3 item 5).

shared1000 and twp1000 are stored *disembodied*: an item with features and
no history. In the experiment each was presented to a subject at a specific
time, in a run, after specific other items. This module reads BIDS
``events.tsv`` files — psytwill's third input class, after extractor CSVs and
the registry — resolves every presentation to a registry ``stimulus_id``, and
emits the presented sequence with the contextual features that exist only
once items are placed in time:

* ``lag_trials`` — stimulus presentations since this item was last shown,
  counted across every events file given (sessions included);
* ``lag_seconds`` — seconds since it was last shown, defined only when the
  previous presentation was in the same run (runs share no clock);
* ``prev_session`` / ``prev_run`` — where the previous presentation was, so
  a session lag is derivable post hoc;
* optionally, cosine distance of the item's embedding in one chosen space to
  the mean of the preceding *k* items in the run (``--context-model``).

The join uses §4.2's verified events→id rules, with the registry README
authoritative: TB/FIN image trials by ``mmmId``; TB/FIN word trials by
``(word, voice)``; NAT movie trials by case-insensitive ``movie_name`` against
``movie_name`` and the closed ``movie_name_variants`` set. An events row that
should resolve and does not is an error naming the reference — a dropped
presentation is exactly the silent failure the registry exists to prevent.

**The boundary is unchanged.** Time here is experimental time — onsets as the
events file records them. HRF convolution, TR resampling and anything with a
brain target are Contract C and braintwill's.

The dense (NAT movie) half of the item — shifting a movie's frame-grid
features by its onset in the run — is not built here. Movie presentations
resolve and get lags like any other item; their within-movie timeline goes
through :mod:`psytwill.project` when a consumer asks for it.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional, Sequence

import numpy as np
import pandas as pd

from psytwill import __version__
from psytwill.exceptions import InputError

TIMELINES_SCHEMA_VERSION = "1.0"

#: Registry tables (contracts §4.2), file name -> the column carrying the
#: value events reference.
REGISTRY_TABLES = {
    "shared1000": "shared1000.tsv",
    "twp1000": "twp1000.tsv",
    "movies": "movies.tsv",
}

#: events ``trial_type`` -> stimulus set. Rows with any other trial type
#: (rest, math, fixation, title, ...) are kept as non-stimulus rows.
STIMULUS_TRIAL_TYPES = {"image": "shared1000", "word": "twp1000", "movie": "movies"}

#: Fixed leading columns of the output, in order. Every events column not
#: consumed by the join is appended after them, unchanged.
TIMELINE_COLUMNS = [
    "subject", "session", "task", "run", "row_idx", "presentation_idx",
    "onset", "duration", "trial_type", "is_stimulus", "stimulus_set",
    "stimulus_id", "voice", "n_prior", "lag_trials", "lag_seconds",
    "prev_session", "prev_run",
]
KEY_COLUMNS = ["subject", "session", "task", "run", "row_idx"]

#: events columns the join consumes; everything else passes through.
_CONSUMED = {"onset", "duration", "trial_type", "mmmId", "word", "voice", "movie_name"}

_ENTITY_RE = re.compile(
    r"sub-(?P<subject>[^_]+)_ses-(?P<session>[^_]+)_task-(?P<task>[^_]+)"
    r"(?:_run-(?P<run>[^_]+))?_events\.tsv$"
)


# --------------------------------------------------------------------------
# registry
# --------------------------------------------------------------------------

@dataclass
class Registry:
    """The three dataset-owned ``stimulus_id`` tables, as lookup maps."""

    path: Path
    by_mmm_id: dict[int, str] = field(default_factory=dict)
    words: set[str] = field(default_factory=set)
    by_movie_name: dict[str, str] = field(default_factory=dict)
    rows: dict[str, int] = field(default_factory=dict)

    @classmethod
    def from_dir(cls, path: str | Path) -> "Registry":
        path = Path(path)
        missing = [f for f in REGISTRY_TABLES.values() if not (path / f).exists()]
        if missing:
            raise InputError(
                f"Registry at {path} lacks {missing}. The registry is dataset-owned "
                "(stimuli/stimulus_registry/), generated by mmmdata's "
                "build_stimulus_registry.py; point --registry at that directory."
            )
        reg = cls(path=path)
        shared = pd.read_csv(path / REGISTRY_TABLES["shared1000"], sep="\t", dtype=str)
        _require(shared, ["stimulus_id", "mmmId"], REGISTRY_TABLES["shared1000"])
        reg.by_mmm_id = {int(m): s for m, s in zip(shared["mmmId"], shared["stimulus_id"])}
        twp = pd.read_csv(path / REGISTRY_TABLES["twp1000"], sep="\t", dtype=str)
        _require(twp, ["stimulus_id"], REGISTRY_TABLES["twp1000"])
        reg.words = set(twp["stimulus_id"])
        movies = pd.read_csv(path / REGISTRY_TABLES["movies"], sep="\t", dtype=str).fillna("")
        _require(movies, ["stimulus_id", "movie_name"], REGISTRY_TABLES["movies"])
        for _, row in movies.iterrows():
            names = [row["movie_name"]] + [
                v for v in str(row.get("movie_name_variants", "")).split("|") if v
            ]
            for name in names:
                key = name.strip().lower()
                if key in reg.by_movie_name and reg.by_movie_name[key] != row["stimulus_id"]:
                    raise InputError(
                        f"movies.tsv: '{name}' maps to both {reg.by_movie_name[key]} "
                        f"and {row['stimulus_id']}; the variant set must be unambiguous."
                    )
                reg.by_movie_name[key] = row["stimulus_id"]
        reg.rows = {"shared1000": len(shared), "twp1000": len(twp), "movies": len(movies)}
        return reg

    def resolve(self, stimulus_set: str, row: pd.Series) -> tuple[str, Optional[str]]:
        """``(stimulus_id, voice)`` for one events row, or raise KeyError."""
        if stimulus_set == "shared1000":
            raw = row.get("mmmId")
            if _isna(raw):
                raise KeyError("image trial without an mmmId")
            sid = self.by_mmm_id.get(int(float(raw)))
            if sid is None:
                raise KeyError(f"mmmId {int(float(raw))} not in shared1000.tsv")
            return sid, None
        if stimulus_set == "twp1000":
            word, voice = row.get("word"), row.get("voice")
            if _isna(word):
                raise KeyError("word trial without a word")
            if _isna(voice):
                raise KeyError(f"word '{word}' without a voice (the twp rule is (word, voice))")
            if str(word) not in self.words:
                raise KeyError(f"word '{word}' not in twp1000.tsv")
            return str(word), str(voice)
        if stimulus_set == "movies":
            name = row.get("movie_name")
            if _isna(name) or not str(name).strip():
                raise KeyError("movie trial without a movie_name")
            sid = self.by_movie_name.get(str(name).strip().lower())
            if sid is None:
                raise KeyError(f"movie_name '{name}' not in movies.tsv (name or variants)")
            return sid, None
        raise KeyError(f"unknown stimulus set {stimulus_set!r}")


def _require(df: pd.DataFrame, cols: list[str], name: str) -> None:
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise InputError(f"{name} lacks columns {missing}; have {list(df.columns)}")


def _isna(v: Any) -> bool:
    if v is None:
        return True
    if isinstance(v, float) and np.isnan(v):
        return True
    return str(v).strip().lower() in {"", "n/a", "nan", "none"}


# --------------------------------------------------------------------------
# events -> presentations
# --------------------------------------------------------------------------

def parse_entities(path: str | Path) -> dict[str, Optional[str]]:
    m = _ENTITY_RE.search(Path(path).name)
    if not m:
        raise InputError(
            f"{Path(path).name} is not a BIDS events file name "
            "(sub-XX_ses-YY_task-T[_run-RR]_events.tsv); entities are read from the name."
        )
    return m.groupdict()


def _stimulus_set_for(row: pd.Series) -> Optional[str]:
    tt = row.get("trial_type")
    if not _isna(tt):
        return STIMULUS_TRIAL_TYPES.get(str(tt))
    # No trial_type: fall back to which reference the row carries.
    if not _isna(row.get("movie_name")):
        return "movies"
    if not _isna(row.get("mmmId")):
        return "shared1000"
    if not _isna(row.get("word")):
        return "twp1000"
    return None


def read_events(paths: Sequence[str | Path], registry: Registry) -> pd.DataFrame:
    """Every row of every events file, resolved, in presentation order.

    Order is (session, run, onset, file row). Session and run sort as
    integers when they are digits, so ``ses-10`` follows ``ses-09``.
    """
    frames = []
    unresolved: list[str] = []
    for p in paths:
        p = Path(p)
        ents = parse_entities(p)
        ev = pd.read_csv(p, sep="\t", na_values=["n/a"], dtype={"word": str, "voice": str, "movie_name": str})
        for col in ("onset", "duration"):
            if col not in ev.columns:
                raise InputError(f"{p.name} lacks required BIDS column {col!r}")
        sets, sids, voices = [], [], []
        for i, row in ev.iterrows():
            sset = _stimulus_set_for(row)
            if sset is None:
                sets.append(None); sids.append(None); voices.append(None)
                continue
            try:
                sid, voice = registry.resolve(sset, row)
            except KeyError as exc:
                unresolved.append(f"{p.name} row {i} ({sset}): {exc}")
                sets.append(sset); sids.append(None); voices.append(None)
                continue
            sets.append(sset); sids.append(sid); voices.append(voice)
        ev = ev.copy()
        ev["stimulus_set"] = sets
        ev["stimulus_id"] = sids
        ev["voice"] = voices  # the resolved voice replaces the raw column
        for k, v in ents.items():
            ev[k] = v
        ev["_file_order"] = np.arange(len(ev))
        frames.append(ev)
    if unresolved:
        shown = "\n  ".join(unresolved[:20])
        more = "" if len(unresolved) <= 20 else f"\n  ... and {len(unresolved) - 20} more"
        raise InputError(
            f"{len(unresolved)} stimulus reference(s) did not resolve against the registry:\n  "
            f"{shown}{more}\nEither the events file is wrong or the registry is stale "
            "(regenerate with build_stimulus_registry.py --check)."
        )
    if not frames:
        raise InputError("no events files given")
    tl = pd.concat(frames, ignore_index=True)
    tl["_ses_sort"] = tl["session"].map(_sortable)
    tl["_run_sort"] = tl["run"].map(_sortable)
    tl = tl.sort_values(["_ses_sort", "_run_sort", "onset", "_file_order"], kind="stable")
    tl = tl.drop(columns=["_ses_sort", "_run_sort", "_file_order"]).reset_index(drop=True)
    tl["row_idx"] = np.arange(len(tl))
    tl["is_stimulus"] = tl["stimulus_id"].notna()
    return tl


def _sortable(v: Any) -> tuple[int, Any]:
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return (0, "")
    s = str(v)
    return (1, int(s)) if s.isdigit() else (2, s)


# --------------------------------------------------------------------------
# contextual features
# --------------------------------------------------------------------------

def add_lags(tl: pd.DataFrame) -> pd.DataFrame:
    """``presentation_idx``, ``n_prior``, ``lag_trials``, ``lag_seconds``, ``prev_*``.

    Identity is ``stimulus_id`` alone: the same word in another voice is the
    same item. ``lag_trials`` counts stimulus presentations (rows with an id)
    between the two showings, across everything given. ``lag_seconds`` is the
    onset difference when the previous showing was in the same session and
    run, else NaN — onsets in different runs share no clock.
    """
    tl = tl.copy()
    stim = tl["is_stimulus"].to_numpy()
    pres_idx = np.full(len(tl), np.nan)
    pres_idx[stim] = np.arange(int(stim.sum()))
    tl["presentation_idx"] = pres_idx

    n_prior = np.full(len(tl), np.nan)
    lag_trials = np.full(len(tl), np.nan)
    lag_seconds = np.full(len(tl), np.nan)
    prev_ses: list[Optional[str]] = [None] * len(tl)
    prev_run: list[Optional[str]] = [None] * len(tl)
    last: dict[str, tuple[int, float, str, Optional[str], int]] = {}
    count: dict[str, int] = {}
    for i in np.flatnonzero(stim):
        sid = tl.at[i, "stimulus_id"]
        n_prior[i] = count.get(sid, 0)
        if sid in last:
            p_idx, p_onset, p_ses, p_run, _ = last[sid]
            lag_trials[i] = pres_idx[i] - p_idx
            if p_ses == tl.at[i, "session"] and p_run == tl.at[i, "run"]:
                lag_seconds[i] = float(tl.at[i, "onset"]) - p_onset
            prev_ses[i] = p_ses
            prev_run[i] = p_run
        last[sid] = (pres_idx[i], float(tl.at[i, "onset"]), tl.at[i, "session"], tl.at[i, "run"], i)
        count[sid] = count.get(sid, 0) + 1
    tl["n_prior"] = n_prior
    tl["lag_trials"] = lag_trials
    tl["lag_seconds"] = lag_seconds
    tl["prev_session"] = prev_ses
    tl["prev_run"] = prev_run
    return tl


def load_item_features(
    features_path: str | Path, models: Optional[Sequence[str]] = None
) -> tuple[pd.DataFrame, dict[str, list[str]]]:
    """Item-level rows of a psytwill ``features`` table, pivoted wide.

    Only untimed rows qualify (``time``, ``onset`` and ``offset`` all null):
    a timeline attaches features *of the item*, not of a moment within it.
    Returns the wide frame keyed by ``(stimulus_id, voice)`` and the
    model -> feature-columns map.
    """
    p = Path(features_path)
    if p.suffix == ".parquet":
        long = pd.read_parquet(p)
    else:
        long = pd.read_csv(p)
    need = {"stimulus_id", "model", "feature", "value"}
    if not need <= set(long.columns):
        raise InputError(
            f"{p.name} is not a psytwill features table (needs {sorted(need)}); "
            "build one with `psytwill features`."
        )
    untimed = long
    for col in ("time", "onset", "offset"):
        if col in untimed.columns:
            untimed = untimed[untimed[col].isna()]
    if models:
        unknown = sorted(set(models) - set(untimed["model"].unique()))
        if unknown:
            raise InputError(
                f"models {unknown} have no item-level rows in {p.name}; available: "
                f"{sorted(untimed['model'].unique())}"
            )
        untimed = untimed[untimed["model"].isin(models)]
    if untimed.empty:
        raise InputError(f"{p.name} has no item-level (untimed) feature rows to attach")
    if "voice" not in untimed.columns:
        untimed = untimed.assign(voice=None)
    wide = untimed.pivot_table(
        index=["stimulus_id", "voice"], columns="feature", values="value",
        aggfunc="first", dropna=False,
    ).reset_index()
    wide.columns.name = None
    model_cols = {
        m: sorted(untimed.loc[untimed["model"] == m, "feature"].unique().tolist())
        for m in untimed["model"].unique()
    }
    return wide, model_cols


def attach_features(tl: pd.DataFrame, wide: pd.DataFrame) -> pd.DataFrame:
    """Left-join item features onto the timeline.

    Voice-specific rows (twp1000 audio spaces) join on ``(stimulus_id,
    voice)``; voice-less rows join on ``stimulus_id`` alone. A stimulus row
    with no features in the table keeps NaN — presence is the store's
    statement, not the timeline's.
    """
    feats = [c for c in wide.columns if c not in ("stimulus_id", "voice")]
    voiced = wide[wide["voice"].notna()]
    unvoiced = wide[wide["voice"].isna()].drop(columns=["voice"])
    out = tl.copy()
    if not unvoiced.empty:
        out = out.merge(unvoiced, on="stimulus_id", how="left")
    if not voiced.empty:
        vcols = [c for c in feats if voiced[c].notna().any()]
        v = voiced[["stimulus_id", "voice"] + vcols]
        out = out.merge(v, on=["stimulus_id", "voice"], how="left", suffixes=("", "__voiced"))
        for c in vcols:
            dup = f"{c}__voiced"
            if dup in out.columns:
                out[c] = out[c].where(out[c].notna(), out[dup])
                out = out.drop(columns=[dup])
    return out


def add_context_distance(tl: pd.DataFrame, model: str, cols: Sequence[str], k: int) -> pd.DataFrame:
    """Cosine distance from each item to the mean of the preceding *k* items.

    Context is the preceding *k* stimulus presentations **in the same
    session and run** that carry this model's features; the first item of a
    run has no context and gets NaN. Column: ``ctx_{model}_k{k}_cosdist``.
    """
    if k < 1:
        raise InputError("--context-k must be >= 1")
    missing = [c for c in cols if c not in tl.columns]
    if missing:
        raise InputError(f"model {model!r}: feature columns not attached: {missing[:5]}")
    name = f"ctx_{model}_k{k}_cosdist"
    out = np.full(len(tl), np.nan)
    X = tl[list(cols)].to_numpy(dtype=float)
    for (_, _), idx in tl.groupby(["session", "run"], sort=False, dropna=False).indices.items():
        history: list[np.ndarray] = []
        for i in idx:
            if not tl.at[i, "is_stimulus"]:
                continue
            x = X[i]
            if np.isnan(x).any():
                continue
            if history:
                ctx = np.mean(history[-k:], axis=0)
                denom = np.linalg.norm(x) * np.linalg.norm(ctx)
                out[i] = 1.0 - float(x @ ctx / denom) if denom > 0 else np.nan
            history.append(x)
    tl = tl.copy()
    tl[name] = out
    return tl


# --------------------------------------------------------------------------
# assembly
# --------------------------------------------------------------------------

def build_timeline(
    events: Sequence[str | Path],
    registry_dir: str | Path,
    output: str | Path,
    features: Optional[str | Path] = None,
    models: Optional[Sequence[str]] = None,
    context_model: Optional[str] = None,
    context_k: int = 5,
) -> dict[str, Any]:
    """The ``timelines`` verb: events + registry [+ features] -> one table + sidecar."""
    registry = Registry.from_dir(registry_dir)
    tl = add_lags(read_events(events, registry))

    model_cols: dict[str, list[str]] = {}
    if features is not None:
        wide, model_cols = load_item_features(features, models)
        tl = attach_features(tl, wide)
    if context_model is not None:
        if features is None:
            raise InputError("--context-model needs --features to supply the embedding")
        if context_model not in model_cols:
            raise InputError(
                f"--context-model {context_model!r} is not among the attached models "
                f"{sorted(model_cols)}"
            )
        tl = add_context_distance(tl, context_model, model_cols[context_model], context_k)

    # Fixed columns first, passthrough after, feature columns last.
    passthrough = [
        c for c in tl.columns
        if c not in TIMELINE_COLUMNS and c not in _CONSUMED
        and not any(c in v for v in model_cols.values()) and not c.startswith("ctx_")
    ]
    feature_cols = [c for v in model_cols.values() for c in v if c in tl.columns]
    ctx_cols = [c for c in tl.columns if c.startswith("ctx_")]
    tl = tl[TIMELINE_COLUMNS + passthrough + feature_cols + ctx_cols]

    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    if output.suffix == ".parquet":
        tl.to_parquet(output, index=False)
    elif output.suffix in (".csv", ".tsv"):
        tl.to_csv(output, index=False, sep="\t" if output.suffix == ".tsv" else ",")
    else:
        raise InputError(f"output must be .parquet, .csv or .tsv, got {output.suffix!r}")

    n_stim = int(tl["is_stimulus"].sum())
    meta = {
        "schema_version": TIMELINES_SCHEMA_VERSION,
        "table": "timelines",
        "extractor": "psytwill",
        "extractor_version": __version__,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "output": {
            "path": str(output.resolve()),
            "rows": int(len(tl)),
            "presentations": n_stim,
            "columns": list(tl.columns),
            "key_columns": KEY_COLUMNS,
        },
        "inputs": {
            "events": [str(Path(p).resolve()) for p in events],
            "registry": {"path": str(Path(registry_dir).resolve()), "rows": registry.rows},
            "features": None if features is None else str(Path(features).resolve()),
            "models": sorted(model_cols),
        },
        "context": None if context_model is None else {"model": context_model, "k": context_k},
        "sets": tl.loc[tl["is_stimulus"], "stimulus_set"].value_counts().to_dict(),
        "time_semantics": "experimental time: onsets as recorded in events.tsv; "
        "lag_seconds only within one run; no HRF, no TR (Contract C).",
    }
    meta_path = output.with_suffix(".meta.json")
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)
    return {
        "output": str(output),
        "meta_path": str(meta_path),
        "rows": int(len(tl)),
        "presentations": n_stim,
        "sets": meta["sets"],
        "models": sorted(model_cols),
    }
